# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Add Flutter to Existing App Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Add Flutter to Existing App Example
  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  
  install_all_flutter_pods(flutter_application_path)
  
  target 'Add Flutter to Existing App ExampleTests' do
    inherit! :search_paths
    install_all_flutter_pods(flutter_application_path)
    # Pods for testing
  end

  target 'Add Flutter to Existing App ExampleUITests' do
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

end
